### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ErikEJ**
Added SQLIte Toolbox and chinnok sample database

### CODE REVIEW

**Comment by geraldb** [comment]
Great. Thanks. Cheers.

**Comment by ErikEJ** [comment]
@geraldb Not sure what the difference between major and minor tools are, though...

**Comment by geraldb** [comment]
Good point. The idea is major are kind of "A" league and minor "B" league.  For something more concrete - the tool is "A" league if it is open source (and works ;-)).  Another is how popular (hard to say). Not sure if that makes sense. Thanks again for your additions. Great stuff the sample online music database (script). Cheers.

**Comment by ErikEJ** [comment]
@geraldb  Thanks, well mine is open source and works! :-)

**Pull request merged**
